services:
  - type: web
    name: excavator-game
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SDL_VIDEODRIVER
        value: "dummy"
      - key: OPENCV_VIDEOIO_PRIORITY_MSMF
        value: "0"
