services:
  # Static site for the HTML
    - type: web
      name: rednode-excavation-site
    runtime: static
      repo: https://github.com/SECUREA1/REDNODE-EXCAVATION.git
    branch: main
    buildCommand: ""
    staticPublishPath: .
    previews:
      generation: automatic

  # Node WebSocket fanout
    - type: web
      name: rednode-excavation-ws
    runtime: node
      repo: https://github.com/SECUREA1/REDNODE-EXCAVATION.git
    rootDir: ws-server
    plan: starter
    buildCommand: npm ci
    startCommand: node server.js
    healthCheckPath: /healthz
